---
# Install aptitude
- name: check if aptitude is installed
  command: which aptitude
  ignore_errors: True
  changed_when: False
  register: aptitude_installed
- name: install aptitude
  command: apt-get install aptitude -y
  when: aptitude_installed.rc == 1

# Install common dependencies
- name: update package repo
  apt: update_cache=yes upgrade=safe
- name: install apt common packages
  apt: name={{item}} state=installed
  with_items:
    - acl  # required by Ansible 2.1 to become_user
    - apt-transport-https
    - build-essential
    - python3
    - python3-pip
    - curl
    - git
    - ntp
    - supervisor
    - emacs24-nox
    - vim
- name: install virtualenv
  pip: name=virtualenv extra_args="--upgrade" executable=pip3

# Common configuration
- name: set timezone variables
  copy:
    content: "Europe/Paris\n"
    dest: "/etc/timezone"
    owner: root
    group: root
    mode: 0644
  notify: update_timezone
- name: generate locale
  locale_gen: name=en_US.UTF-8 state=present
- name: set locale
  copy:
    content: "LANG=en_US.UTF-8\nLC_ALL=en_US.UTF-8"
    dest: "/etc/default/locale"
    owner: root
    group: root
    mode: 0644
- name: set default editor to emacs
  alternatives:
    name: editor
    path: "/usr/bin/emacs"

# User configuration
- name: create user
  user: name="{{app_user}}" shell="/bin/bash"
- name: copy github credential token
  template:
    src: dotnetrc
    dest: /home/{{app_user}}/.netrc
    owner: "{{app_user}}"
    mode: 0600
- name: install emacs conf & color scheme
  unarchive:
    src: emacs.tgz
    dest: /home/{{ app_user }}
    creates: /home/{{ app_user }}/.emacs.d/themes/tangotango-theme.el
    owner: "{{ app_user }}"
- name: install vim conf & color scheme
  unarchive:
    src: vim.tgz
    dest: /home/{{ app_user }}
    creates: /home/{{ app_user }}/.vim/colors/jellybeans.vim
    owner: "{{ app_user }}"
