---
- name: update yum cache
  yum:
    update_cache: yes

- name: install yum common dependencies
  yum:
    name:
      - htop
      - python2-pip

# Timezone
- name: set timezone to Europe/Paris
  timezone:
    name: Europe/Paris
...
