---
- name: install docker pip dependency
  pip:
    name: docker
    state: latest

- name: install docker
  yum:
    name:
      - docker

- name: install daemon.json
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0744
  notify: restart docker service

- name: enable and start service docker
  service:
    name: docker
    state: started
    enabled: yes
...
