os: linux
arch:
  - arm64

language: python
python:
  - "3.9"
env:
  - REPO=maur1th/naxos-forum SRC=app/forum
  - REPO=maur1th/naxos-websocket SRC=app/websocket

# App
services:
  - docker
script:
  - docker build --build-arg VERSION=$TRAVIS_COMMIT --tag $REPO $SRC
  - docker tag $REPO{,:$TRAVIS_COMMIT}
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO:$TRAVIS_COMMIT
  - docker push $REPO

notifications:
  email: false
