dist: trusty
sudo: required

language: python
python:
  - "3.6"
env:
  - REPO=maur1th/naxos-forum SRC=app/forum
  - REPO=maur1th/naxos-websocket SRC=app/websocket

# SonarQube
addons:
  sonarqube:
    organization: default

# App
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
script:
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build --tag $REPO:$TAG $SRC
  - if [ -n "$TRAVIS_TAG" ]; then
    docker tag $REPO:$TAG $REPO:$TRAVIS_TAG;
    fi
  - sonar-scanner
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO

# jobs:
#   include:
#     - stage: deploy
#       deploy:
#         on:
#           branch: master
#         provider: script
#         script:
#           - pip3 install $ANSIBLE
#           - echo $PRIVATE_KEY > /private_key
#           - echo $VAULT_PASS > /vault_pass
#           - ansible-playbook site.yml \
#               --inventory-file=hosts-prod \
#               --vault-password-file=/vault_pass \
#               --private-key=/private_key \
#               --extra-vars="version=latest"
#       env: ANSIBLE="ansible<2.4"

notifications:
  email: false
