dist: trusty
sudo: required

language: python
python:
  - "3.6"
env:
  - REPO=maur1th/naxos-forum SRC=app/forum
  - REPO=maur1th/naxos-websocket SRC=app/websocket

# SonarQube
addons:
  sonarqube:
    organization: default

# App
services:
  - docker
script:
  - export TAG=`if [ -n "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo $TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER; fi`
  - docker build --build-arg VERSION=$TAG --tag $REPO:$TAG $SRC
  - sonar-scanner
after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push $REPO

# jobs:
#   include:
#     - stage: deploy
#       deploy:
#         on:
#           branch: master
#         provider: script
#         script:
#           - pip3 install $ANSIBLE
#           - echo $PRIVATE_KEY > /private_key
#           - echo $VAULT_PASS > /vault_pass
#           - ansible-playbook site.yml \
#               --inventory-file=hosts-prod \
#               --vault-password-file=/vault_pass \
#               --private-key=/private_key \
#               --extra-vars="version=latest"
#       env: ANSIBLE="ansible<2.4"

notifications:
  email: false
