---
version: "3"
services:
  forum:
    build: app/forum
    entrypoint: python3 manage.py runserver 0.0.0.0:5000
    volumes:
      - ./app/forum:/app
    environment:
      DEBUG: "True"
      AWS_STORAGE_BUCKET_NAME: geekattitude
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - db
      - memcached
    restart: always
  websocket:
    build: app/websocket
    volumes:
      - ./app/websocket:/app
  db:
    image: postgres:9.6-alpine
    volumes:
      - forum-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: crimson
    restart: always
  memcached:
    image: memcached:1.4-alpine
    restart: always
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/data/static:ro
    ports:
      - "8080:80"
    depends_on:
      - forum
      - websocket
    restart: always
volumes:
  forum-db: {}
...
