version: "3"
services:
  forum:
    build: app/naxos
    volumes:
      - ./app/naxos:/app
    expose:
      - "5000"
    environment:
      HOSTNAME: forum
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: crimson
      CACHE_LOCATION: memcached
    depends_on:
      - db
      - memcached
    restart: always
  db:
    image: postgres:9.6-alpine
    volumes:
      - forum-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: crimson
    restart: always
  memcached:
    image: memcached:1.4-alpine
    restart: always
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/static:/data/static:ro
    ports:
      - "8080:80"
    depends_on:
      - forum
    restart: always
volumes:
  forum-db: {}
