---
version: "3.1"

services:

  forum:
    build:
      context: app/forum
      args:
        LOCAL_ENV: 1
    environment:
      DEBUG: 1
      INTERNAL_IP: 172.18.0.1
    volumes:
      - ./app/forum:/app
      - forum-media:/app/media
    depends_on:
      - db
      - memcached
    restart: always

  websocket:
    build: app/websocket

  db:
    image: postgres:9.6-alpine
    volumes:
      - forum-db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: crimson
    restart: always

  memcached:
    image: memcached:1.4-alpine
    restart: always

  nginx:
    image: nginx:1.12-alpine
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./app/forum/static_root:/data/static:ro
      - forum-media:/data/media:ro
    ports:
      - "8080:80"
    depends_on:
      - forum
      - websocket
    restart: always

  prometheus:
    image: prom/prometheus
    volumes:
      - ./conf/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./conf/django.rules.yml:/etc/prometheus/django.rules.yml:ro
      - prometheus:/prometheus
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "9091:3000"

volumes:
  forum-db: {}
  forum-media: {}
  prometheus: {}
  grafana-storage: {}
...
