---
- name: load vaulted variables
  include_vars: vault/main.yml

# Directories setup
- name: create global directory
  file:
    path: "{{project_dir}}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_user}}"
- name: create log directory
  file:
    path: /var/log/{{project_name}}
    state: directory
    group: "{{app_user}}"
    owner: "{{app_user}}"
    mode: 0755
- name: store user configuration
  template:
    src: "{{item.name}}"
    dest: /home/{{app_user}}/{{item.dest}}
    owner: "{{app_user}}"
    mode: 0600
  with_items:
    - { name: "sh_env", dest: ".bash_profile" }
- name: clone git repo
  become_user: "{{app_user}}"
  git:
    repo: "{{repo}}"
    dest: "{{project_dir}}"
    version: "{{branch}}"
    update: yes
    force: yes
    recursive: no
  when: env_type != "dev"

# Dependencies
- name: install apt packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - python3
    - python3-pip
    - virtualenv
    - python-imaging
    - libjpeg-dev
    - libtiff5-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - nginx
    - postgresql
    - postgresql-server-dev-9.4
    - memcached
    - libmemcached-dev
- name: install pip dependencies
  pip:
    extra_args: "--upgrade"
    requirements: "{{project_dir}}requirements/{{env_type}}.txt"
    virtualenv: "{{project_dir}}env"
    virtualenv_python: python3
- name: install node dependencies
  become_user: "{{app_user}}"
  command: /usr/bin/yarn chdir={{project_dir}}naxos/nodejs/

# Django setup
- name: set up django settings module
  template:
    src: django-settings.py
    dest: "{{project_dir}}naxos/naxos/settings.py"
    owner: "{{app_user}}"
    mode: 0600
- name: copy ad html snippets
  copy:
    src: "{{item}}"
    dest: "{{project_dir}}naxos/templates/ads/"
    owner: "{{app_user}}"
    mode: 0600
  with_items:
    - amazon.html
    - paypal_gift.html

# Gunicorn setup
- name: create bin/ directory
  file:
    path: "{{project_dir}}bin/"
    owner: "{{app_user}}"
    state: directory
    mode: 0700
- name: set up gunicorn start script
  template:
    src: gunicorn_start
    dest: "{{project_dir}}bin/"
    owner: "{{app_user}}"
    mode: 0700

# Nginx conf
- name: remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  notify: restart_nginx
- name: add site in nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/sites-enabled/{{project_name}}.conf"
    mode: 0644
  notify: restart_nginx
