---
- name: load vaulted variables
  include_vars: vault/main.yml

- name: install apt packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - python3
    - python3-pip
    - virtualenvwrapper
    - python-imaging
    - libjpeg-dev
    - libtiff5-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - nginx
    - postgresql
    - postgresql-server-dev-9.3
    - memcached
    - libmemcached-dev
    - supervisor

- name: Create global directory
  file:
    path: "{{project_dir}}"
    state: directory
    owner: "{{app_user}}"
    group: "{{app_user}}"
- name: create log directory
  file:
    path: /var/log/{{project_name}}
    state: directory
    group: "{{app_user}}"
    owner: "{{app_user}}"
    mode: 0755

- name: copy django settings module
  template:
    src: django-settings.py
    dest: "{{project_dir}}/naxos/naxos/settings/local.py"
