---
# Install project-specific packages
- name: install packages
  apt:
    name: "{{item}}"
    state: installed
  with_items:
    - python3
    - python3-pip
    - virtualenvwrapper
    - python-imaging
    - libjpeg-dev
    - libtiff5-dev
    - libfreetype6-dev
    - liblcms2-dev
    - libwebp-dev
    - nginx
    - postgresql
    - postgresql-server-dev-9.3
    - memcached
    - libmemcached-dev
    - supervisor
