---
- name: check if volume ({{volume}}) exists
  command: docker volume inspect {{volume}}
  register: result
  ignore_errors: True
  changed_when: False
- name: create volume ({{volume}})
  command: docker volume create {{volume}}
  when: result|failed
- name: stop db container
  docker_container:
    name: db
    state: absent
  ignore_errors: yes
  register: container_stop
  until: not container_stop.get("failed")
  retries: 5
  delay: 10
- name: start db container
  docker_container:
    name: db
    image: postgres:{{postgres_version}}
    pull: yes
    state: started
    networks:
      - name: "{{project_name}}"
        aliases:
          - db
    volumes:
      - "{{volume}}:/var/lib/postgresql/data"
...
