---
- hosts: app
  become: yes
  vars:
    network: "{{project_name}}"
  roles:
    - name: common
    - name: docker
      version: "17.12"
    - name: docker_network
    - name: db
      version: "10.1"
    - name: memcached
      version: "1.5"
    - name: forum
      version: "{{app_version}}"
    - name: certbot-ovh
      domain: "{{inventory_hostname}}"
    - name: nginx
      version: "1.12"
    - name: metrics
      prometheus_version: latest  # until they have a better taging policy
      cadvisor_version: latest    # ...
  tasks:
    # Reclaim hard drive space
    - name: clean outdated docker images & stopped containers
      shell: >
        docker system prune --force &&
        docker rmi $(docker images --quiet --filter dangling=true)
      failed_when: False
...
