---
- hosts: all
  become: yes
  roles:
    - common
    - db
    - forum
    - nginx
    - metrics
  tasks:
    # Reclaim hard drive space
    - name: clean outdated docker images & stopped containers
      shell: >
        docker system prune --force &&
        docker rmi $(docker images --quiet --filter dangling=true)
      failed_when: False
...
