---
# Apply db migrations
- name: initial migration of db
  become_user: "{{app_user}}"
  shell: >
    DJANGO_SETTINGS_MODULE=naxos.settings
    {{project_dir}}env/bin/python manage.py migrate
  args:
    chdir: "{{project_dir}}naxos/"

# Load initial data
- name: load initial data (fixtures)
  become_user: "{{app_user}}"
  shell: >
    DJANGO_SETTINGS_MODULE=naxos.settings
    {{project_dir}}env/bin/python manage.py loaddata {{item}}
  args:
    chdir: "{{project_dir}}naxos/"
  with_items:
    - categories.json

# Create test user
- name: copy create_test_user script
  copy:
    src: create_test_user.py
    dest: "{{project_dir}}naxos/"
    owner: "{{app_user}}"
    mode: 0700
  when: env_type == "dev"
- name: create test user
  become_user: "{{app_user}}"
  shell: >
    DJANGO_SETTINGS_MODULE=naxos.settings
    {{project_dir}}env/bin/python create_test_user.py
  args:
    chdir: "{{project_dir}}naxos/"
  when: env_type == "dev"
- name: delete create_test_user script
  file: path={{project_dir}}naxos/create_test_user.py state=absent
