---
- name: load vaulted variables
  include_vars: vars/vault.yml

- name: copy ad html snippets
  copy:
    src: "{{item}}"
    dest: "/tmp/ads/"
  with_items:
    - amazon.html
    - paypal_gift.html

- name: launch forum container
  docker_container:
    name: forum
    image: "{{forum_image}}:{{version}}"
    state: started
    networks:
      - name: "{{project_name}}"
        aliases:
          - "{{forum_host}}"
    env:
      HOSTNAME: "{{inventory_hostname}}"
      DEBUG_MODE: "{{debug_mode}}"
      ADMIN_NAME: "{{admin_name}}"
      ADMIN_EMAIL: "{{admin_email}}"
      DB_NAME: "{{db_name}}"
      DB_USER: "{{db_user}}"
      DB_PASSWORD: "{{db_password}}"
      DB_HOST: "{{db_host}}"
      DB_PORT: "{{db_port}}"
      CACHE_LOCATION: "{{cache_host}}"
      EMAIL_HOST: "{{email_host}}"
      EMAIL_PORT: "{{email_port}}"
      SERVER_EMAIL: "{{server_email}}"  # email address to use
      EMAIL_HOST_PASSWORD: "{{email_host_password}}"
      EMAIL_SERVER_PREFIX: "{{email_server_prefix}}"
      AWS_STORAGE_BUCKET_NAME: "{{aws_storage_bucket_name}}"
      AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
      AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
    volumes:
      - /tmp/ads:/app/templates/ads/:ro
...
