---
# Nginx config and certificates
- name: create host nginx folder
  file:
    state: directory
    path: "{{nginx_folder}}"
- name: copy dhparam
  copy:
    src: dhparam.pem
    dest: "{{nginx_folder}}/"
- name: install nginx conf
  template:
    src: nginx.conf
    dest: "{{nginx_folder}}/"

# Nginx
- name: stop nginx container
  docker_container:
    name: nginx
    state: absent
  ignore_errors: yes
  register: container_stop
  until: not container_stop.get("failed")
  retries: 5
  delay: 10
- name: start nginx container
  docker_container:
    name: nginx
    image: nginx:{{version}}
    pull: yes
    state: started
    restart_policy: unless-stopped
    networks:
      - name: "{{network}}"
        aliases:
          - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "{{nginx_folder}}/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "{{nginx_folder}}/dhparam.pem:/etc/nginx/ssl/dhparam.pem:ro"
      - "/etc/letsencrypt:/etc/letsencrypt:ro"

# Cron
- name: Add nginx reload cron job
  cron:
    name: reload nginx
    minute: "10"
    hour: "4"
    job: docker kill --signal=SIGHUP nginx
...
